export const ADD_VALUE='ADD_VALUE'
export const SUB_VALUE='SUB_VALUE'
export const LOGIN_USER='LOGIN_USER'
export const LOGIN_ERROR='LOGIN_ERROR'
export const LOGIN_USER_UPDATE='LOGIN_USER_UPDATE'


export const LOGIN_ADMIN='LOGIN_ADMIN'
export const LOGIN_ADMIN_ERROR='LOGIN_ADMIN_ERROR'

export const REGISTER_USER='REGISTER_USER'
export const REGISTER_ERROR='REGISTER_ERROR'

export const REGISTER_ADMIN='REGISTER_ADMIN'
export const REGISTER_ADMIN_ERROR='REGISTER_ADMIN_ERROR'

export const BET_EN='BET_EN'
export const BET_ERROR='MATCH_ERROR'

export const GAME_TYPE='GAME_TYPE'

export const SET_GAME_TYPE='SET_GAME_TYPE'


export const GET_DEPOSIT_INFO='GET_DEPOSIT_INFO'
export const GET_DEPOSIT_INFO_ERROR='GET_DEPOSIT_INFO_ERROR'

export const ADMIN_GET_DEPOSIT_INFO='ADMIN_GET_DEPOSIT_INFO'
export const ADMIN_GET_DEPOSIT_INFO_ERROR='ADMIN_GET_DEPOSIT_INFO_ERROR'

export const GET_TRANSFER_INFO='GET_TRANSFER_INFO'
export const GET_TRANSFER_INFO_ERROR='GET_TRANSFER_INFO_ERROR'

export const ADMIN_GET_TRANSFER_INFO='ADMIN_GET_TRANSFER_INFO'
export const ADMIN_GET_TRANSFER_INFO_ERROR='ADMIN_GET_TRANSFER_INFO_ERROR'

export const GET_WITHDRAW_INFO='GET_WITHDRAW_INFO'
export const GET_WITHDRAW_INFO_ERROR='GET_WITHDRAW_INFO_ERROR'

export const ADMIN_GET_WITHDRAW_INFO='ADMIN_GET_WITHDRAW_INFO'
export const ADMIN_GET_WITHDRAW_INFO_ERROR='ADMIN_GET_WITHDRAW_INFO_ERROR'

export const GET_PLACE_BETS_INFO='GET_PLACE_BETS_INFO'
export const GET_PLACE_BETS_INFO_ERROR='GET_PLACE_BETS_INFO_ERROR'


export const ADMIN_ACCOUNT_TYPE='ADMIN_ACCOUNT_TYPE';
export const ADMIN_ACCOUNT_TYPE_ERROR='ADMIN_ACCOUNT_TYPE_ERROR'


export const ADMIN_LIST='ADMIN_LIST'
export const ADMIN_LIST_ERROR='ADMIN_LIST_ERROR'

export const USER_LIST='USER_LIST'
export const USER_LIST_ERROR='USER_LIST_ERROR'


export const ADMIN_STACKNAME='ADMIN_STACKNAME'
export const ADMIN_STACKNAME_ERROR="ADMIN_STACKNAME_ERROR"

export const ADMIN_STACK='ADMIN_STACK'
export const ADMIN_STACK_ERROR="ADMIN_STACKNAME"


export const ADMIN_BET='ADMIN_BET'
export const ADMIN_FINISHED_BET='ADMIN_FINISHED_BET'
export const ADMIN_UPCOMMING_BET='ADMIN_UPCOMMING_BET'
export const ADMIN_HIDDEN_BET='ADMIN_HIDDEN_BET'

export const ADMIN_BET_ERROR='ADMIN_LIVE_BET_ERROR'
export const ADMIN_UPCOMMING_BET_ERROR='ADMIN_UPCOMMING_BET_ERROR'
export const ADMIN_HIDDEN_BET_ERROR='ADMIN_HIDDEN_BET_ERROR'

export const ADMIN_BET_SINGLE_LIST='ADMIN_BET_SINGLE_LIST'

export const ADMIN_PLACE_BETS='ADMIN_PLACE_BETS';
export const ADMIN_PLACE_BETS_ERROR='ADMIN_PLACE_BETS_ERROR';


export const ADMIN_GENERAL_SETTINGS='ADMIN_GENERAL_SETTINGS'
export const ADMIN_GENERAL_SETTINGS_ERROR='ADMIN_GENERAL_SETTINGS_ERROR'

export const ADMIN_COLOR_SETTINGS='ADMIN_COLOR_SETTINGS'
export const ADMIN_COLOR_SETTINGS_ERROR='ADMIN_COLOR_SETTINGS_ERROR'

export const ADMIN_DASHBOARD='ADMIN_DASHBOARD';
export const ADMIN_DASHBOARD_ERROR='ADMIN_DASHBOARD_ERROR'

export const GET_IMAGE='GET_IMAGE'
export const GET_IMAGE_ERROR='GET_IMAGE_ERROR'



export const ADMIN_LUDO_GET='ADMIN_LUDO_GET'
export const ADMIN_LUDO_GET_ERROR='ADMIN_LUDO_GET_ERROR'

export const ADMIN_LUDO_LIST_GET='ADMIN_LUDO_LIST_GET'

export const ADMIN_LUDO_POST='ADMIN_LUDO_POST'
export const ADMIN_LUDO_POST_ERROR='ADMIN_LUDO_POST_ERROR'




export const LUDO_RATE_GET='LUDO_RATE_GET'
export const LUDO_RATE_GET_ERROR='LUDO_RATE_GET'

export const LUDO_PLAY='LUDO_PLAY'
export const LUDO_PLAY_ERROR='LUDO_PLAY_ERROR'


export const COIN_RATE_GET='COIN_RATE_GET'
export const COIN_PLAY='COIN_PLAY'
export const COIN_PLAY_ERROR='COIN_PLAY_ERROR'

export const EVEN_RATE_GET='EVEN_RATE_GET'
export const EVEN_PLAY='EVEN_PLAY'
export const EVEN_PLAY_ERROR='EVEN_PLAY_ERROR'

export const CARD_RATE_GET='CARD_RATE_GET'
export const CARD_PLAY='CARD_PLAY'
export const CARD_PLAY_ERROR='CARD_PLAY_ERROR'
export const CARD_ADD='CARD_ADD'
export const CARD_CLEAN='CARD_CLEAN'


export const GAME_BETS='GAME_BETS';
export const GAME_BETS_ERROR='GAME_BETS_ERROR';



export const WHEEL_RATE_GET='WHEEL_RATE_GET'
export const WHEEL_RATE_GET_ERROR='WHEEL_RATE_GET'

export const WHEEL_PLAY='WHEEL_PLAY'
export const WHEEL_PLAY_ERROR='WHEEL_PLAY_ERROR'





export const ADMIN_WHEEL_GET='ADMIN_WHEEL_GET'
export const ADMIN_WHEEL_GET_ERROR='ADMIN_WHEEL_GET_ERROR'

export const ADMIN_WHEEL_LIST_GET='ADMIN_WHEEL_LIST_GET'

export const ADMIN_WHEEL_POST='ADMIN_WHEEL_POST'
export const ADMIN_WHEEL_POST_ERROR='ADMIN_WHEEL_POST_ERROR'

export const ADMIN_COIN_GET='ADMIN_COIN_GET'
export const ADMIN_COIN_ERROR='ADMIN_COIN_ERROR'
export const ADMIN_COIN_LIST_GET='ADMIN_COIN_LIST_GET'

export const ADMIN_EVEN_GET='ADMIN_EVEN_GET'
export const ADMIN_EVEN_ERROR='ADMIN_EVEN_ERROR'
export const ADMIN_EVEN_LIST_GET='ADMIN_EVEN_LIST_GET'

export const ADMIN_CARD_GET='ADMIN_CARD_GET'
export const ADMIN_CARD_ERROR='ADMIN_CARD_ERROR'
export const ADMIN_CARD_LIST_GET='ADMIN_CARD_LIST_GET'



export const SLIDER_IMAGE='ADMIN_SLIDER_IMAGE'
export const ADMIN_SLIDER_IMAGE_ERROR='ADMIN_SLIDER_IMAGE_ERROR'


export const ADMIN_GET_PROMOCODE='ADMIN_GET_PROMOCODE';
export const ADMIN_SET_PROMOCODE='ADMIN_SET_PROMOCODE';
export const ADMIN_PROMOCODE_ERROR='ADMIN_PROMOCODE_ERROR';


export const ADMIN_GET_NOTIFICATIONS='ADNMIN_GET_NOTIFICATIONS'
export const ADMIN_NOTIFICATIONS_ERROR='ADNMIN_NOTIFICATIONS_ERROR'


export const GET_NOTIFICATIONS='GET_NOTIFICATIONS'
export const NOTIFICATIONS_ERROR='NOTIFICATIONS_ERROR'



export const CLUB_LOGIN_USER='CLUB_LOGIN_USER'
export const CLUB_LOGIN_ERROR='CLUB_LOGIN_ERROR'
export const CLUB_LOGIN_USER_UPDATE='CLUB_LOGIN_USER_UPDATE'

export const USER_GET_CLUB_LIST='USER_GET_CLUB_LIST'
export const USER_GET_CLUB_LIST_ERROR='USER_GET_CLUB_LIST_ERROR'

export const CLUB_MEMBER_LIST='CLUB_MEMBER_LIST';
export const CLUB_MEMBER_BET_LIST='CLUB_MEMBER_BET_LIST';
export const CLUB_MEMBER_LIST_ERROR='CLUB_MEMBER_LIST_ERROR';


export const CLUB_WITHDRAW_INFO='CLUB_WITHDRAW_INFO'
export const CLUB_WITHDRAW_INFO_ERROR='CLUB_WITHDRAW_INFO_ERROR'

export const ADMIN_CLUB_LIST='ADMIN_CLUB_LIST'
export const ADMIN_CLUB_LIST_ERROR='ADMIN_CLUB_LIST_ERROR'

export const CLUB_SEND_MESSAGE='CLUB_SEND_MESSAGE';
export const CLUB_RECEIVE_MESSAGE='CLUB_RECEIVE_MESSAGE';
export const CLUB_MESSAGE_ERROR='CLUB_MESSAGE_ERROR';

export const ADMIN_CLUB_RECEIVE_MESSAGE='ADMIN_CLUB_RECEIVE_MESSAGE';
export const ADMIN_CLUB_SEND_MESSAGE='ADMIN_CLUB_SEND_MESSAGE';
export const ADMIN_CLUB_MESSAGE_ERROR='ADMIN_CLUB_MESSAGE_ERROR';

export const CLUB_DASHBOARD='CLUB_DASHBOARD';
export const CLUB_DASHBOARD_ERROR='CLUB_DASHBOARD_ERROR';


export const ADMIN_FINANCE='ADMIN_FINANCE';
export const ADMIN_FINANCE_ERROR='ADMIN_FINANCE_ERROR';